Traceback (most recent call last):
  File "/Users/victorfrancis/Downloads/Data Engineer Test/test.py", line 4, in <module>
    import pandasa as pd
ModuleNotFoundError: No module named 'pandasa'
Traceback (most recent call last):
  File "/Users/victorfrancis/Downloads/Data Engineer Test/test.py", line 4, in <module>
    import pandasa as pd
ModuleNotFoundError: No module named 'pandasa'
Traceback (most recent call last):
  File "/Users/victorfrancis/Downloads/Data Engineer Test/test.py", line 4, in <module>
    import pandasa as pd
ModuleNotFoundError: No module named 'pandasa'
Traceback (most recent call last):
  File "/Users/victorfrancis/Downloads/Data Engineer Test/test.py", line 4, in <module>
    import pandasa as pd
ModuleNotFoundError: No module named 'pandasa'
Traceback (most recent call last):
  File "/Users/victorfrancis/Downloads/Data Engineer Test/test.py", line 4, in <module>
    import pandasa as pd
ModuleNotFoundError: No module named 'pandasa'
Traceback (most recent call last):
  File "/Users/victorfrancis/Downloads/Data Engineer Test/test.py", line 4, in <module>
    import pandasa as pd
ModuleNotFoundError: No module named 'pandasa'
Traceback (most recent call last):
  File "/Users/victorfrancis/Downloads/Data Engineer Test/test.py", line 4, in <module>
    import pandasa as pd
ModuleNotFoundError: No module named 'pandasa'
Traceback (most recent call last):
  File "/Users/victorfrancis/Downloads/Data Engineer Test/test.py", line 4, in <module>
    import pandasa as pd
ModuleNotFoundError: No module named 'pandasa'
Traceback (most recent call last):
  File "/Users/victorfrancis/Downloads/Data Engineer Test/test.py", line 4, in <module>
    import pandasa as pd
ModuleNotFoundError: No module named 'pandasa'
